language: php
sudo: false

php:
  - 5.5
  - 5.6
  - 7.0

env:
  global:
      - secure: "kK4CVy7xWpjzNcdFOV5DLkO50SoCYnCSRqzTUffc6x+thBBouj//sSSW4oNlM5k2RN6VFozL/ZvWXqE4sXq2WeYqH9S7ZNYbMK2xdAvH/nszfQdV5itjyL5S6u4Qe4z2R2zDLzhMSzVXGwIKbVTQnRdYlKveEjj20bz8D2kbidI="

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env:
        - GUZZLE="~5.0"
        - SYMFONY_EVENT_DISPATCHER="~2.0"
    - php: 5.5
      env:
        - GUZZLE="~5.0"
        - SYMFONY_EVENT_DISPATCHER="~2.0"
    - php: 5.6
      env:
        - GUZZLE="~5.0"
        - SYMFONY_EVENT_DISPATCHER="~2.0"
    - php: 5.6
      env:
        - GUZZLE="~5.0"
        - SYMFONY_EVENT_DISPATCHER="~2.0"
    - php: 7.0
      env:
        - GUZZLE="~5.0"
        - SYMFONY_EVENT_DISPATCHER="~2.0"
    - php: 7.0
      env:
        - GUZZLE="~5.0"
        - SYMFONY_EVENT_DISPATCHER="~2.0"

install:
  - composer selfupdate
  - composer config -g github-oauth.github.com $GH_TOKEN
  - composer install --prefer-source
  - if [[ $GUZZLE != '' ]]; then composer require --prefer-source --no-update "guzzlehttp/guzzle:$GUZZLE" ; fi
  - if [[ $SYMFONY_EVENT_DISPATCHER != '' ]]; then composer require --prefer-source --no-update "symfony/event-dispatcher:$SYMFONY_EVENT_DISPATCHER" ; fi

addons:
  code_climate:
    repo_token: 303a289e61e8e11d8bcae115860c4fffc6e1e7fe2d504d20a773e69bd7641284

after_script:
  - vendor/bin/test-reporter
